name: CI Pipeline

on:
  pull_request:
    type: [ opened, synchronize ]


jobs:
  ci-pipeline:
    - uses: .github/workflows/setup-python-env.yml
    - name: Run flake8
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      run: flake8 ${{ steps.filter.outputs.py_modified_files }}
    - name: Run pytest
      if: ${{ steps.filter.outputs.py_modified == 'true' }}
      run: pytest tests
